export const SET_DIS_SHOW_LOADER = "SET_DIS_SHOW_LOADER"

export const SET_DIS_SHOW_LOADER_TEXT = "SET_DIS_SHOW_LOADER_TEXT"

export const SET_USER_DATA = "SET_USER_DATA"

export const SET_TESTED_DATA = "SET_TESTED_DATA"

export const REMOVE_USER_DATA = "REMOVE_USER_DATA"

export const SET_COMMENT_SHOW = "SET_COMMENT_SHOW"

export const SET_COMMENT_VALUE = "SET_COMMENT_VALUE"

export const SET_COMMENT_EDIT = "SET_COMMENT_EDIT"

